version: "3"
services:
  db:
    image: mongo
    container_name: "mongo"
    volumes:
      - ./data:/data/db
  
  api:
    image: vanhtuan/dockertutorial
    container_name: "dockertutorial"
    build: .
    environment:
      - MONGODB_HOST=db
      - MONGODB_PORT=27017
      - MONGODB_DB=dockertutorial
    ports:
      - 8000:8000
    depends_on:
      - db
